---
title: "HCOMPC"
author: "Ethan Ashby"
date: "2/21/2021"
output: pdf_document
---

```{r}
library(variantprobs)
library(tidyverse)
library(data.table)
library(SAMBAR)
library(gplots)
source("calc_minfo copy.R")
library(scales)
library(WGCNA)
library(dynamicTreeCut)
`%!in%` = Negate(`%in%`)
foo<-function(){}
tcga<-variantprobs::tcga
```

```{r defining modules}
tcga_v_f <- suppressWarnings(tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
    ][, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), n_tumor = n_tumor[1]),
                          by = .(Variant, Hugo_Symbol, Cancer_Code)
                          ])

tcga_v_f<-tcga_v_f[Hugo_Symbol %in% SAMBAR::genes,]

tcga_v_f$Cancer_Code<-factor(tcga_v_f$Cancer_Code, levels=sort(unique(tcga_v_f$Cancer_Code)))

cancer_probs<-tcga_v_f %>% select(Cancer_Code, n_tumor) %>% distinct() %>% arrange(.$Cancer_Code) %>% summarize(n_tumor/sum(n_tumor)) %>% unlist()
names(cancer_probs)<-sort(unique(tcga_v_f$Cancer_Code))

GT_probs=suppressMessages(suppressWarnings(tcga_v_f[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Hugo_Symbol, Cancer_Code)
      ]))

GT_probs_1<-suppressMessages(GT_probs          %>%
    dcast(
      Hugo_Symbol ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>%
    magrittr::set_rownames(.$Hugo_Symbol) %>%
    .[, Hugo_Symbol := NULL] %>%
    data.matrix())

gene_spec_nmis<-calc_minfo(GT_probs_1, cancer_probs, normalize=TRUE)

####
#calculate and hclust with angular distance of GT probs
cor_mat<-cor(t(GT_probs_1))
ang_dist<-acos(cor_mat)
hc1<-hclust(as.dist(ang_dist))
plot(hc1, labels=FALSE)
cut<-dynamicTreeCut::cutreeHybrid(hc1, distM=ang_dist, minClusterSize = 3)
png("hclust_hybrid.png", units="in", width=8, height=6, res=300)
WGCNA::plotDendroAndColors(hc1, colors=cut$labels, dendroLabels=FALSE)
dev.off()

#identify correlated modules
groups<-rep(list(NA), max(cut$labels))
for(i in 1:max(cut$labels)){
  groups[[i]]<-rownames(GT_probs_1[which(cut$labels==i),])
}

#################
#depsarse plot
################

tcga_v_f <- suppressWarnings(tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
    ][, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), n_tumor = n_tumor[1]),
                          by = .(Variant, Hugo_Symbol, Cancer_Code)
                          ])

#tcga[MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
#] %>% group_by(patient_id, Cancer_Code) %>% #dplyr::summarize('Num-genes'=length(unique(Hugo_Symbol))) %>% ggplot(aes(x=Cancer_Code, y=`Num-genes`, fill=Cancer_Code))+geom_violin()+theme_bw()+scale_y_continuous(trans="log10")+theme(axis.text.x = element_text(angle=90), legend.position="none", panel.grid=element_blank(), axis.title.x = element_blank())+ylab("Number of mutated genes")

a<-tcga[MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
]
a$patient_id<-factor(a$patient_id, levels=unique(a$patient_id))

tmp_plot<-lapply(1:length(groups), FUN=function(i){
  if(i %% 100 ==0){print(i)}
  genes_of_interest<-groups[[i]]
  tmp<-a[Hugo_Symbol %in% genes_of_interest,]
  tmp$Hugo_Symbol<-paste("Mod", i, sep="_")
  tmp
})

tmp_plot<-do.call("rbind", tmp_plot)

#tmp_plot %>% group_by(patient_id, Cancer_Code) %>% dplyr::summarize('Num-path'=length(unique(Hugo_Symbol))) %>% ggplot(aes(x=Cancer_Code, y=`Num-path`, fill=Cancer_Code))+geom_violin()+theme_bw()+scale_y_continuous(trans="log10")+theme(axis.text.x = element_text(angle=90), legend.position="none", panel.grid=element_blank(), axis.title.x = element_blank())+ylab("Number of mutated pathways")

tmp_plot_genes<-a[Hugo_Symbol %in% SAMBAR::genes,] %>% dplyr::group_by(patient_id, Cancer_Code, .drop=FALSE) %>% dplyr::summarize('Num-genes'=length(unique(Hugo_Symbol))) %>% cbind(. , Lev="Gene")

tmp_plot_pathways<-tmp_plot[!is.na(Cancer_Code),] %>% dplyr::group_by(patient_id, Cancer_Code, .drop=FALSE) %>% dplyr::summarize('Num-genes'=length(unique(Hugo_Symbol))) %>% cbind(. , Lev="Pathway")

#png("desparse_plot_.png", units="in", width=8, height=5, res=300)
#rbind(tmp_plot_genes, tmp_plot_pathways) %>% filter(!is.na(Cancer_Code)) %>% ggplot(aes(x=Cancer_Code, y=`Num-genes`, fill=Cancer_Code))+geom_violin()+theme_bw()+scale_y_continuous(trans=scales::pseudo_log_trans(base = 10), breaks = c(1, 10, 100, 1000, 10000))+theme(axis.text.x = element_text(angle=90), legend.position="none", panel.grid=element_blank(), axis.title.x = element_blank())+ylab("Number of mutated features per tumor")+facet_grid(rows=vars(Lev), cols=NULL)
#dev.off()


###calculate pathway-specific GT probs
GT_probs<-lapply(1:length(groups), FUN=function(i){
  if(i%%10==0){print(i)}
  genes_of_interest<-groups[[i]]
  tmp<-tcga_v_f[Hugo_Symbol %in% genes_of_interest,]
  tmp$Hugo_Symbol<-paste("Mod", i, sep="_")
  tmp$Cancer_Code<-factor(tmp$Cancer_Code, levels=sort(unique(tcga_v_f$Cancer_Code)))
  GT_probs_tmp=suppressMessages(suppressWarnings(tmp[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Cancer_Code)
      ]))
  
  GT_probs_tmp$Mod<-paste("Mod", i, sep="_")
  
  GT_probs_tmp_1<-suppressMessages(GT_probs_tmp          %>%
    dcast(
      Mod ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>% magrittr::set_rownames(.$Mod) %>%
    .[, Mod := NULL] %>%
    data.matrix())
  
  return(GT_probs_tmp_1)
})

GT_probs<-do.call(rbind, GT_probs)



######
#heatmap

library(RColorBrewer)
coul<- colorRampPalette(brewer.pal(20, "YlOrRd"))(25)
png("path_heatmap_HCOMPC.png", units="in", width=8, height=8, res=300)
heatmap(GT_probs, Rowv=TRUE, Colv=NA, col=coul, scale="row", labRow=FALSE)
dev.off()

#####
#cor with TMB
scalar1<-function(x){x/sqrt(sum(x^2))}
TMB_vec<-tcga_v_f %>% dplyr::group_by(Cancer_Code) %>% dplyr::summarize(TMB=sum(v_f)/n_tumor[1]) %>% .$TMB %>% scalar1()


cors_with_TMB<-lapply(1:dim(GT_probs)[1], FUN=function(i) cor(TMB_vec, GT_probs[i,]))
png("cor_with_TMB_HCOMPC.png", units="in", width=8, height=6, res=300)
ggplot(data=NULL)+geom_histogram(aes(x=unlist(cors_with_TMB), fill=unlist(cors_with_TMB)<quantile(cors_with_TMB %>% unlist(), 0.05)), bins=50)+theme_minimal()+xlab("Corr. with TMB")+geom_vline(aes(xintercept=quantile(cors_with_TMB %>% unlist(), 0.05)))+scale_fill_manual(values=c("black", "red"))+theme(legend.position = "none")
dev.off()


####
#TMB breakers bubb plot
####
##
png("bubb_HCOMPC.png", units="in", width=8, height=6, res=300)
GT_probs[which(cors_with_TMB<quantile(cors_with_TMB %>% unlist(), 0.05)),] %>% melt() %>% ggplot(aes(x=Var2, y=Var1, color=Var1, size=value))+geom_point()+theme_minimal()+theme(legend.position="none", axis.text.x=element_text(angle=90), axis.title=element_blank())
dev.off()

#pca<-princomp(GT_probs)
#autoplot(pca)
#biplot(pca)
#cor(pca$loadings[,1], TMB_vec)

####
#nmis
nmis_HCOMPC<-calc_minfo(GT_probs, cancer_prob=cancer_probs, normalize=TRUE)

#pca<-princomp(GT_probs)
#g<-ggplot(data=pca, aes(x=pca$scores[,1], y=pca$scores[,2], text=rownames(pca$scores)))+geom_point()+xlab("Comp. 1")+ylab("Comp. 2")
#ggplotly(g, tooltip="text")
#biplot(pca)
#cor(pca$loadings[,1], TMB_vec)

#GT_probs[which(rownames(GT_probs) %in% names(sort(nmis_HCOMPC, decreasing=TRUE))[1:5]),] %>% melt() %>% ggplot(aes(x=Var2, y=Var1, color=Var1, size=value))+geom_point()+theme_minimal()+theme(legend.position="none", axis.text.x=element_text(angle=90))
```

```{r NULL}
set.seed(11)

setDTthreads(0)

tcga_samp<-tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
    ] %>% select(patient_id, Cancer_Code) %>% distinct()

tcga_null<-tcga

tcga_null<-lapply(1:length(groups), FUN=function(i){
  tmp<-tcga_null[Hugo_Symbol %in% groups[[i]],]
  tmp$Hugo_Symbol<-paste("Mod", i, sep="_")
  tmp})
tcga_null<-do.call("rbind", tcga_null)

############
#crank out null iterations

null_nmis_HCOMPC<-mclapply(1:100, FUN=function(i){
  #scramble tissue labels associated with each tumor
  
  tcga_samp$Cancer_Code<-sample(tcga_samp$Cancer_Code, replace=FALSE)

  tcga_p<-left_join(tcga_null[MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),][,c(1,2,3)], tcga_samp, by='patient_id')
  
  tcga_v_f_p<-suppressWarnings(tcga_p[, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), Hugo_Symbol=Hugo_Symbol[1], n_tumor = n_tumor[1]),
                          by = .(Variant, Cancer_Code)
                          ])
  
#calc GT probs

GT_probs_perm=suppressMessages(suppressWarnings(tcga_v_f_p[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Hugo_Symbol, Cancer_Code)
      ]))

GT_probs_1_perm<-suppressMessages(GT_probs_perm          %>%
    dcast(
      Hugo_Symbol ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>%
    magrittr::set_rownames(.$Hugo_Symbol) %>%
    .[, Hugo_Symbol := NULL] %>%
    data.matrix())
  
  calc_minfo(GT_probs_1_perm, cancer_prob=cancer_probs, normalize=TRUE)}, mc.cores = 8)


to_plot_nmi<-data.frame("val"=c(unlist(null_nmis_HCOMPC), nmis_HCOMPC), "id"=c(rep("Null", length(unlist(null_nmis_HCOMPC))), rep("True", length(nmis_HCOMPC))))

png("null_nmi_HCOMPC.png", units="in", width=6, height=4, res=300)
ggplot()+geom_histogram(data=to_plot_nmi[which(to_plot_nmi$id=="Null"),], aes(x=val, y=stat(count)/sum(count)), fill="blue", alpha=0.5, bins=100)+geom_histogram(data=to_plot_nmi[which(to_plot_nmi$id=="True"),], aes(x=val, y=stat(count)/sum(count)), fill="red", alpha=0.5, bins=100)+theme_classic()+geom_vline(aes(xintercept=quantile(unlist(null_nmis_HCOMPC), 0.99)), lty=2)+theme(legend.position="none")+xlab("NMI")+ylab("Relative Frequency")
dev.off()


#GT_probs[which(rownames(GT_probs) %in% names(sort(nmis_HCOMPC, decreasing=TRUE)[110:120])),] %>% melt() %>% ggplot(aes(x=Var2, y=Var1, size=value, color=Var1))+geom_point()+theme_minimal()+theme(legend.position="none", axis.text.x=element_text(angle=90), axis.title = element_blank())
```

#Validate signals

```{r}
set.seed(12345)
#split into 50-50 bins
ids<-unique(tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & Cancer_Code %in% c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC")
    ]$patient_id)
train_ids<-sample(ids, length(ids)/2, replace=FALSE)
test_ids<-setdiff(ids, train_ids)

#####
#train probs

tcga_v_f_train <- suppressWarnings(tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & Cancer_Code %in% c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC") & patient_id %in% train_ids,
    ][, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), n_tumor = n_tumor[1]),
                          by = .(Variant, Hugo_Symbol, Cancer_Code)
                          ])

tcga_v_f_train<-tcga_v_f_train[Hugo_Symbol %in% SAMBAR::genes,]

GT_probs_train=suppressMessages(suppressWarnings(tcga_v_f_train[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Hugo_Symbol, Cancer_Code)
      ]))

GT_probs_train<-suppressMessages(GT_probs_train          %>%
    dcast(
      Hugo_Symbol ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>%
    magrittr::set_rownames(.$Hugo_Symbol) %>%
    .[, Hugo_Symbol := NULL] %>%
    data.matrix())

  cor_mat<-cor(t(GT_probs_train))
  ang_dist<-acos(cor_mat)
  hc1<-hclust(as.dist(ang_dist))
  #plot(hc1, labels=FALSE)
  cut<-dynamicTreeCut::cutreeHybrid(hc1, distM=ang_dist, minClusterSize = 3)
  #png("hclust_hybrid.png", units="in", width=8, height=6, res=300)
  #WGCNA::plotDendroAndColors(hc1, colors=cut$labels, dendroLabels=FALSE)
  #dev.off()

  #identify correlated modules
  groups<-rep(list(NA), max(cut$labels))
  for(i in 1:max(cut$labels)){
    groups[[i]]<-rownames(GT_probs_1[which(cut$labels==i),])
  }
  
  GT_probs_train<-lapply(1:length(groups), FUN=function(i){
  if(i%%10==0){print(i)}
  genes_of_interest<-groups[[i]]
  tmp<-tcga_v_f_train[Hugo_Symbol %in% genes_of_interest,]
  tmp$Hugo_Symbol<-paste("Mod", i, sep="_")
  tmp$Cancer_Code<-factor(tmp$Cancer_Code, levels=sort(unique(tcga_v_f$Cancer_Code)))
  GT_probs_tmp=suppressMessages(suppressWarnings(tmp[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Cancer_Code)
      ]))
  
  GT_probs_tmp$Mod<-paste("Mod", i, sep="_")
  
  GT_probs_tmp_1<-suppressMessages(GT_probs_tmp          %>%
    dcast(
      Mod ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>% magrittr::set_rownames(.$Mod) %>%
    .[, Mod := NULL] %>%
    data.matrix())
  
  return(GT_probs_tmp_1)
})

GT_probs_train<-do.call(rbind, GT_probs_train)

##########
#test probs

tcga_v_f_test <- suppressWarnings(tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & Cancer_Code %in% c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC") & patient_id %in% test_ids,
    ][, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), n_tumor = n_tumor[1]),
                          by = .(Variant, Hugo_Symbol, Cancer_Code)
                          ])

tcga_v_f_test<-tcga_v_f_test[Hugo_Symbol %in% SAMBAR::genes,]

  GT_probs_test<-lapply(1:length(groups), FUN=function(i){
  if(i%%10==0){print(i)}
  genes_of_interest<-groups[[i]]
  tmp<-tcga_v_f_test[Hugo_Symbol %in% genes_of_interest,]
  tmp$Hugo_Symbol<-paste("Mod", i, sep="_")
  tmp$Cancer_Code<-factor(tmp$Cancer_Code, levels=sort(unique(tcga_v_f$Cancer_Code)))
  GT_probs_tmp=suppressMessages(suppressWarnings(tmp[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Cancer_Code)
      ]))
  
  GT_probs_tmp$Mod<-paste("Mod", i, sep="_")
  
  GT_probs_tmp_1<-suppressMessages(GT_probs_tmp          %>%
    dcast(
      Mod ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>% magrittr::set_rownames(.$Mod) %>%
    .[, Mod := NULL] %>%
    data.matrix())
  
  return(GT_probs_tmp_1)
})
  
  GT_probs_test<-do.call(rbind, GT_probs_test)
  
############
#compare
  
  trainprobs<-GT_probs_train %>% melt()
  colnames(trainprobs)<-c("Mod", "Cancer_Type", "x")
  testprobs<-GT_probs_test %>% melt()
  colnames(testprobs)<-c("Mod", "Cancer_Type", "y")
  
  library(epiR)
  Lins<-epi.ccc(left_join(trainprobs, testprobs)$x, left_join(trainprobs, testprobs)$y)
  
  left_join(trainprobs, testprobs) %>% ggplot(aes(x=x, y=y, color=Cancer_Type))+geom_point()+coord_fixed()+geom_abline(aes(intercept=0, slope=1))+annotate(geom="text", x=0.1, y=0.4, label=paste("Lin's CC: ", round(Lins$rho.c[1], 3)),
              color="red")+theme_minimal()+xlab("GT from Train")+ylab("GT from Test")


###########
#true validation
  
to_filt<-tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & Cancer_Code %in% c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC")]
to_filt$Cancer_Code<-factor(to_filt$Cancer_Code, levels=c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC"))

valid_probs<-lapply(1:length(groups), FUN=function(i){
  if(i%%10==0){print(i)}
  genes_of_interest<-groups[[i]]
  tmp <-  suppressMessages(to_filt[patient_id %in% test_ids & Hugo_Symbol %in% genes_of_interest & Variant %!in% tcga_v_f_train$Variant,
    ] %>% group_by(Cancer_Code, .drop=FALSE) %>% summarize(num=length(unique(patient_id))))
  denom<-suppressMessages(to_filt[patient_id %in% test_ids,] %>% group_by(Cancer_Code, .drop=FALSE) %>% summarize(denom=length(unique(patient_id))))
  tmp$num/denom$denom
})

valid_probs<-do.call(rbind, valid_probs)
rownames(valid_probs)<-paste("Mod", 1:dim(valid_probs)[1], sep="_")
colnames(valid_probs)<-c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC")

valid=valid_probs %>% melt()
colnames(valid)<-c("Mod", "Cancer_Type", "y")

Lins<-epi.ccc(left_join(trainprobs, valid)$x, left_join(trainprobs, valid)$y)

png("HCOMPC_valid.png", units="in", width=8, height=8, res=300)
left_join(trainprobs, valid) %>% tibble() %>% ggplot(aes(x=x, y=y, color=Cancer_Type))+geom_point()+coord_fixed()+geom_abline(aes(intercept=0, slope=1))+annotate(geom="text", x=0.1, y=0.4, label=paste("Lin's CC: ", round(Lins$rho.c[1], 3)),
              color="red")+theme_minimal()+xlab("Estimated from Train")+ylab("Observed in Test")
dev.off()
```

