---
title: "Pathways"
author: "Ethan Ashby"
date: "2/4/2021"
output: html_document
---

```{r}
library(variantprobs)
library(tidyverse)
library(data.table)
library(SAMBAR)
library(gplots)
source("calc_minfo copy.R")
library(scales)
`%!in%` = Negate(`%in%`)
foo<-function(){}
tcga<-variantprobs::tcga
```

#At least one

##build paths, heatmap, desparse plot
```{r}
set.seed(11)

min.pathway.size=3

#load canonical pathways, all cancer neighborhood/modules, all oncogenic signature gene sets, and all cell type signature gene sets
bin<-SAMBAR::convertgmt("./Pathways/c2.cp.v7.2.symbols.gmt", cagenes=SAMBAR::genes)
bin1<-SAMBAR::convertgmt("./Pathways/c4.all.v7.2.symbols.gmt", cagenes=SAMBAR::genes)
bin2<-SAMBAR::convertgmt("./Pathways/c6.all.v7.2.symbols.gmt", cagenes=SAMBAR::genes)
bin3<-SAMBAR::convertgmt("./Pathways/c8.all.v7.2.symbols.gmt", cagenes=SAMBAR::genes)

#list of pathway genes
path_list<-lapply(list(bin, bin1, bin2, bin3), FUN=function(b){
path_list<-list()
for(i in 1:dim(b)[1]){
  path_list[[i]]<-names(which(b[i,]==1))
}
names(path_list)<-rownames(b)
return(path_list)
})

path_list<-append(append(append(path_list[[1]], path_list[[2]]), path_list[[3]]), path_list[[4]])

#distribution of pathway sizes
ggplot(data=NULL, aes(x=lapply(path_list, length) %>% unlist(), y=..count..))+geom_histogram(binwidth=1)+xlab("Pathway size")+ylab("Frequency")+theme_bw()
ggplot(data=NULL, aes(x=lapply(path_list, length) %>% unlist(), y=..count..))+geom_histogram(binwidth=1)+scale_x_continuous(trans="sqrt")+xlab("Pathway size")+ylab("Frequency")+theme_bw()

pathways<-path_list[which(lapply(path_list, length)>min.pathway.size)]

tcga_v_f <- suppressWarnings(tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
    ][, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), n_tumor = n_tumor[1]),
                          by = .(Variant, Hugo_Symbol, Cancer_Code)
                          ])

tcga_v_f$Cancer_Code<-factor(tcga_v_f$Cancer_Code, levels=sort(unique(tcga_v_f$Cancer_Code)))

cancer_probs<-tcga_v_f %>% select(Cancer_Code, n_tumor) %>% distinct() %>% arrange(.$Cancer_Code) %>% summarize(n_tumor/sum(n_tumor)) %>% unlist()
names(cancer_probs)<-sort(unique(tcga_v_f$Cancer_Code))

#calculating GT probs for our pathways!!!
GT_probs<-lapply(1:length(pathways), FUN=function(i){
  if(i%%100==0){print(i)}
  genes_of_interest<-pathways[[i]]
  tmp<-tcga_v_f[Hugo_Symbol %in% genes_of_interest,]
  tmp$Hugo_Symbol<-names(pathways[i])
  tmp$Cancer_Code<-factor(tmp$Cancer_Code, levels=sort(unique(tcga_v_f$Cancer_Code)))
  GT_probs_tmp=suppressMessages(suppressWarnings(tmp[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Cancer_Code)
      ]))
  
  GT_probs_tmp_1<-suppressMessages(GT_probs_tmp          %>%
    dcast(
      GT ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>%
    .[, GT := NULL] %>%
    data.matrix()) %>% colSums()
  
  GT_probs_tmp_1
})

GT_probs<-do.call("rbind", GT_probs)

rownames(GT_probs)<-names(pathways)
colnames(GT_probs)<-sort(unique(tcga_v_f$Cancer_Code))

library(RColorBrewer)
coul<- colorRampPalette(brewer.pal(20, "YlOrRd"))(25)
png("path_heatmap.png", units="in", width=8, height=8, res=300)
heatmap(GT_probs, Rowv=TRUE, Colv=NA, col=coul, scale="row", labRow=FALSE)
dev.off()

nmis<-calc_minfo(GT_probs, cancer_prob=cancer_probs, normalize=TRUE)

#########
#PCA
########
#library(factoextra)
#pca<-prcomp(GT_probs, scale = TRUE, center=TRUE)
#viz_eig(pca)

#cbind(pca$x[,1:2], nmis) %>% as.data.frame() %>% ggplot(aes(x=PC1, y=PC2, color=nmis))+geom_point()+scale_color_gradient(low="blue", high="red")+ggtitle("PCA of GT vectors")
#fviz_pca_ind(pca,
#             col.ind = "cos2", # Color by the quality of representation
#             geom="point",
#             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
#             repel = FALSE     # Avoid text overlapping,
#             )+ggtitle("PCA of GT vectors")

#bubbleplot

#GT_probs[which(rownames(GT_probs) %in% names(head(sort(nmis, decreasing = TRUE), 40))),] %>% melt() %>% ggplot(aes(x=Var2, y=Var1, size=value, color=value))+geom_point()+theme_dark()+theme(legend.position="none", axis.text.x=element_text(angle=90))+scale_color_gradient2(low="gold", midpoint=0.5, mid="orange", high="red")+scale_y_discrete(label=function(x) abbreviate(x, minlength = 10))
    
###################
#compare mutation frequency in genes per tumor vs pathway

tcga_v_f <- suppressWarnings(tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
    ][, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), n_tumor = n_tumor[1]),
                          by = .(Variant, Hugo_Symbol, Cancer_Code)
                          ])

#tcga[MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
#] %>% group_by(patient_id, Cancer_Code) %>% #dplyr::summarize('Num-genes'=length(unique(Hugo_Symbol))) %>% ggplot(aes(x=Cancer_Code, y=`Num-genes`, fill=Cancer_Code))+geom_violin()+theme_bw()+scale_y_continuous(trans="log10")+theme(axis.text.x = element_text(angle=90), legend.position="none", panel.grid=element_blank(), axis.title.x = element_blank())+ylab("Number of mutated genes")

a<-tcga[MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
]
a$patient_id<-factor(a$patient_id, levels=unique(a$patient_id))

tmp_plot<-lapply(1:length(pathways), FUN=function(i){
  if(i %% 100 ==0){print(i)}
  genes_of_interest<-pathways[[i]]
  tmp<-a[Hugo_Symbol %in% genes_of_interest,]
  tmp$Hugo_Symbol<-names(pathways[i])
  tmp
})

tmp_plot<-do.call("rbind", tmp_plot)

#tmp_plot %>% group_by(patient_id, Cancer_Code) %>% dplyr::summarize('Num-path'=length(unique(Hugo_Symbol))) %>% ggplot(aes(x=Cancer_Code, y=`Num-path`, fill=Cancer_Code))+geom_violin()+theme_bw()+scale_y_continuous(trans="log10")+theme(axis.text.x = element_text(angle=90), legend.position="none", panel.grid=element_blank(), axis.title.x = element_blank())+ylab("Number of mutated pathways")

tmp_plot_genes<-a[Hugo_Symbol %in% SAMBAR::genes,] %>% dplyr::group_by(patient_id, Cancer_Code, .drop=FALSE) %>% dplyr::summarize('Num-genes'=length(unique(Hugo_Symbol))) %>% cbind(. , Lev="Gene")

tmp_plot_pathways<-tmp_plot[!is.na(Cancer_Code),] %>% dplyr::group_by(patient_id, Cancer_Code, .drop=FALSE) %>% dplyr::summarize('Num-genes'=length(unique(Hugo_Symbol))) %>% cbind(. , Lev="Pathway")

png("desparse_plot.png", units="in", width=8, height=5, res=300)
rbind(tmp_plot_genes, tmp_plot_pathways) %>% filter(!is.na(Cancer_Code)) %>% ggplot(aes(x=Cancer_Code, y=`Num-genes`, fill=Cancer_Code))+geom_violin()+theme_bw()+scale_y_continuous(trans=scales::pseudo_log_trans(base = 10), breaks = c(1, 10, 100, 1000, 10000))+theme(axis.text.x = element_text(angle=90), legend.position="none", panel.grid=element_blank(), axis.title.x = element_blank())+ylab("Number of mutated features per tumor")+facet_grid(rows=vars(Lev), cols=NULL)
dev.off()
```

##null NMIs
```{r}
###############################
#Null values for same pathways when we permute tissue labels per tumor

set.seed(11)

setDTthreads(0)

tcga_samp<-tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
    ] %>% select(patient_id, Cancer_Code) %>% distinct()

tcga_null<-tcga

tcga_null<-lapply(1:length(pathways), FUN=function(i){
  tmp<-tcga_null[Hugo_Symbol %in% pathways[[i]],]
  tmp$Hugo_Symbol<-names(pathways[i])
  tmp})
tcga_null<-do.call("rbind", tcga_null)

############
#crank out null iterations

null_nmis<-mclapply(1:1000, FUN=function(i){
  #scramble tissue labels associated with each tumor

  tcga_samp$Cancer_Code<-sample(tcga_samp$Cancer_Code, replace=FALSE)

  tcga_p<-left_join(tcga_null[MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),][,c(1,2,3)], tcga_samp, by='patient_id')
  
  tcga_v_f_p<-suppressWarnings(tcga_p[, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), Hugo_Symbol=Hugo_Symbol[1], n_tumor = n_tumor[1]),
                          by = .(Variant, Cancer_Code)
                          ])
  
#calc GT probs

GT_probs_perm=suppressMessages(suppressWarnings(tcga_v_f_p[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Hugo_Symbol, Cancer_Code)
      ]))

GT_probs_1_perm<-suppressMessages(GT_probs_perm          %>%
    dcast(
      Hugo_Symbol ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>%
    magrittr::set_rownames(.$Hugo_Symbol) %>%
    .[, Hugo_Symbol := NULL] %>%
    data.matrix())
  
  calc_minfo(GT_probs_1_perm, cancer_prob=cancer_probs, normalize=TRUE)}, mc.cores = 8)

#null_nmis %>% unlist() %>% hist()

#NMI plots

ggplot(data.frame(Val=nmis))+geom_histogram(mapping=aes(x=Val, y=..count../sum(..count..), fill="dodgerblue", alpha=0.5))+theme_bw()+geom_vline(xintercept=quantile(unlist(null_nmis), 0.99), col="black", lty=2)+geom_histogram(data=data.frame(Val=unlist(null_nmis)), mapping=aes(x=Val, y=..count../sum(..count..), fill="darkorange", alpha=0.5))+scale_x_continuous(trans="log10")+theme(legend.position = "none")+ylab("Relative Frequency")+xlab("NMI (log-scale)")

#data.frame(Val=nmis) %>% ggplot()+geom_histogram(mapping=aes(x=Val, y=..count../sum(..count..)), fill="dodgerblue")+geom_vline(xintercept=quantile(unlist(null_nmis), 0.99), col="black", lty=2)+theme_bw()
```

## random same sized grouping (depreciated)
```{r}
############
#compare nmis to random groupings (no tiss. label permuting)
set.seed(11)

sizes<-lapply(pathways, length) %>% unlist() %>% unique()

rand_groups<-mclapply(1:100, FUN=function(j){
  samps<-lapply(seq(3, 406, by=20), FUN=function(i){sample(SAMBAR::genes, i)})
  tcga_v_f <- suppressWarnings(tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
    ][, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), n_tumor = n_tumor[1]),
                          by = .(Variant, Hugo_Symbol, Cancer_Code)
                          ])

  tcga_null<-lapply(1:length(samps), FUN=function(i){
    tmp<-tcga_v_f[Hugo_Symbol %in% samps[[i]],]
    tmp$Hugo_Symbol<-paste("Mgene", seq(3, 406, by=20)[i])
    tmp})
tcga_null<-do.call("rbind", tcga_null)

  GT_probs_perm=suppressMessages(suppressWarnings(tcga_null[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Hugo_Symbol, Cancer_Code)
      ]))

  GT_probs_1_perm<-suppressMessages(GT_probs_perm          %>%
    dcast(
      Hugo_Symbol ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>%
    magrittr::set_rownames(.$Hugo_Symbol) %>%
    .[, Hugo_Symbol := NULL] %>%
    data.matrix())
  
    calc_minfo(GT_probs_1_perm, cancer_prob=cancer_probs, normalize=TRUE) %>% sort()}, mc.cores=8)

rand_groups<-do.call("rbind", rand_groups)

quants<-lapply(1:dim(rand_groups)[2], FUN=function(i) quantile(rand_groups[,i],0.99)) %>% unlist()
ggplot(data=NULL, aes(x=seq(3, 406, by=20), y=quants))+geom_line(color="blue")+geom_point(data=NULL, aes(data=NULL, x=unlist(lapply(pathways, length)), y=nmis), alpha=0.2)+theme_bw()+scale_x_continuous(trans="log10")
```

## TMB breakers to null, bubbleplots, word cloud

```{r}
#TMB vector
scalar1<-function(x){x/sqrt(sum(x^2))}
TMB_vec<-tcga_v_f %>% dplyr::group_by(Cancer_Code) %>% dplyr::summarize(TMB=sum(v_f)/n_tumor[1]) %>% .$TMB %>% scalar1()
#names(TMB_vec)<-cancer_nums$Cancer_Code
#barplot(TMB_vec)

TMB_breakers<-names(nmis[which(lapply(1:dim(GT_probs)[1], FUN=function(i) cor(TMB_vec, GT_probs[i,])) %>% unlist() < quantile(unlist(cors), 0.05))])

png("PMBG_bubb.png", units="in", width=8, height=8, res=350)
GT_probs[which(rownames(GT_probs) %in% names(sort(nmis[which(names(nmis) %in% TMB_breakers)], decreasing=TRUE))[1:20]),] %>% melt() %>% ggplot(aes(x=Var2, y=Var1, size=value, color=Var1))+geom_point()+theme_minimal()+theme(legend.position="none", axis.text.x=element_text(angle=90), axis.title=element_blank())+scale_y_discrete(label=function(x) stringr::str_trunc(str_remove_all(x, "REACTOME_|WP_|BIOCARTA_|KEGG_"), 15))
dev.off()

cors<-lapply(1:dim(GT_probs)[1], FUN=function(i) cor(TMB_vec, GT_probs[i,]))
png("cors_with_TMB.png", units="in", width=7, height=5, res=300)
ggplot()+geom_histogram(data=NULL, aes(x=unlist(cors), y=..count.., fill=unlist(cors)>quantile(unlist(cors), 0.05)), binwidth=0.01)+geom_vline(xintercept=quantile(unlist(cors), 0.05))+xlab("Correlations between Mut. Probs and TMB")+ylab("Frequency")+scale_fill_manual(values=c("red", "black"))+theme_minimal()+theme(legend.position='none')
dev.off()


#######
#compare tmb breakers to null permutations

set.seed(11)

setDTthreads(0)

tcga_samp<-tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
    ] %>% select(patient_id, Cancer_Code) %>% distinct()

tcga_null<-tcga

tcga_null<-lapply(1:length(pathways), FUN=function(i){
  tmp<-tcga_null[Hugo_Symbol %in% pathways[[i]],]
  tmp$Hugo_Symbol<-names(pathways[i])
  tmp})
tcga_null<-do.call("rbind", tcga_null)

############
#crank out null iterations

null_nmis<-mclapply(1:100, FUN=function(i){
  #scramble tissue labels associated with each tumor

  tcga_samp$Cancer_Code<-sample(tcga_samp$Cancer_Code, replace=FALSE)

  tcga_p<-left_join(tcga_null[MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),][,c(1,2,3)], tcga_samp, by='patient_id')
  
  tcga_v_f_p<-suppressWarnings(tcga_p[, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), Hugo_Symbol=Hugo_Symbol[1], n_tumor = n_tumor[1]),
                          by = .(Variant, Cancer_Code)
                          ])
  
#calc GT probs

GT_probs_perm=suppressMessages(suppressWarnings(tcga_v_f_p[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Hugo_Symbol, Cancer_Code)
      ]))

GT_probs_1_perm<-suppressMessages(GT_probs_perm          %>%
    dcast(
      Hugo_Symbol ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>%
    magrittr::set_rownames(.$Hugo_Symbol) %>%
    .[, Hugo_Symbol := NULL] %>%
    data.matrix())
  
  calc_minfo(GT_probs_1_perm, cancer_prob=cancer_probs, normalize=TRUE)}, mc.cores = 8)


png("path_at_least_1_nmidists.png", units="in", width=7, height=5.5, res=300)
ggplot(data=NULL)+geom_histogram(data=NULL, aes(x=nmis[which(names(nmis) %in% TMB_breakers)], y=stat(count)/sum(count)), fill="red", alpha=0.5, binwidth=0.0005)+geom_histogram(aes(x=unlist(null_nmis), y=stat(count)/sum(count)), fill="blue", alpha=0.5, binwidth=0.0005)+theme_classic()+geom_vline(aes(xintercept=quantile(unlist(null_nmis), 0.99)), lty=2)+ylab("Relative frequency")+xlab("NMI")
dev.off()

###########
#NMF
##########

#library(NMF)
#rank_est<-nmf(GT_probs, 2:10, nrun=10)
#try<-nmf(GT_probs, rank=7)

#try<-nmf(GT_probs, 6)
#s <- extractFeatures(try, method="max") 
#str(s)

#bubbleplots

GT_probs[which(rownames(GT_probs) %in% names(head(sort(nmis[which(names(nmis) %in% TMB_breakers & nmis>0.01)], decreasing=TRUE), 10))),] %>% melt() %>% ggplot(aes(x=Var2, y=Var1, size=value, color=value))+geom_point()+scale_y_discrete(label=function(x) abbreviate(x, minlength = 16))+theme(legend.position="none", axis.text.x=element_text(angle=90))+scale_color_gradient2(low="gold", midpoint=0.5, mid="orange", high="red")

cor_try<-GT_probs[which(rownames(GT_probs) %in% names(nmis[which(names(nmis) %in% TMB_breakers & nmis>0.01)])),] %>% t() %>% cor() 
cor_try<-1-cor_try
hc<-hclust(as.dist(cor_try))
#plot(hc, labels=FALSE)
#cutree(hc, h=0.5) %>% table()

df<-data.frame("Pathway"=rownames(GT_probs[which(rownames(GT_probs) %in% names(nmis[which(names(nmis) %in% TMB_breakers & nmis>0.01)])),]), "Membership"=cutree(hc, h=0.5), "NMI"=nmis[which(names(nmis) %in% TMB_breakers & nmis>0.01)])

top_paths<-df %>% group_by(Membership) %>% top_n(NMI, n=1) %>% .$Pathway

png("bubb_plot_toppathss.png", units="in", width=6.5, height=5.5, res=300)
GT_probs[which(rownames(GT_probs) %in% top_paths),] %>% melt() %>% ggplot(aes(x=Var2, y=Var1, size=value, color=value))+geom_point()+scale_y_discrete(label=function(x) abbreviate(x, minlength = 20))+theme_minimal()+theme(legend.position="none", axis.text.x=element_text(angle=90), axis.title=element_blank())+scale_color_gradient2(low="gold", midpoint=0.5, mid="orange", high="red")
dev.off()

#GT_probs[which(rownames(GT_probs) %in% top_paths),] %>% melt() %>% ggplot(aes(x=Var2, y=value, color=Var1, group=Var1))+geom_path()+theme(legend.position="none")+scale_y_continuous(trans="log10")+facet_wrap(~Var1)

############
#word cloud of pathways
###########

df$Pathway %>% str_replace_all("_", " ") %>% str_replace_all(c("REACTOME"="", "KEGG"="", "BIOCARTA"="", "MODULE"="","WP"="","MORF"="","PID"="","PATHWAY"="", "AND"="", "THE"="")) %>% paste(collapse=" ") %>% wordcloud::wordcloud(min.freq=4)

png("wordcloud_gene_membs.png", units="in", width=5.5, height=5.5, res=300)
path_list[which(names(path_list) %in% names(nmis[which(names(nmis) %in% TMB_breakers & nmis>0.01)]))] %>% unlist() %>% paste(collapse=" ") %>% wordcloud::wordcloud()
dev.off()
```

## Valid
```{r}
set.seed(12345)
#split into 50-50 bins
ids<-unique(tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & Cancer_Code %in% c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC")
    ]$patient_id)
train_ids<-sample(ids, length(ids)/2, replace=FALSE)
test_ids<-setdiff(ids, train_ids)

#############
#Train probs
#############

tcga_v_f_train <- suppressWarnings(tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & Cancer_Code %in% c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC") & patient_id %in% train_ids,
    ][, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), n_tumor = n_tumor[1]),
                          by = .(Variant, Hugo_Symbol, Cancer_Code)
                          ])

GT_probs_train<-lapply(1:length(pathways), FUN=function(i){
  if(i%%100==0){print(i)}
  genes_of_interest<-pathways[[i]]
  tmp<-tcga_v_f_train[Hugo_Symbol %in% genes_of_interest,]
  tmp$Hugo_Symbol<-names(pathways[i])
  tmp$Cancer_Code<-factor(tmp$Cancer_Code, levels=c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC"))
  GT_probs_tmp=suppressMessages(suppressWarnings(tmp[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[1]),
      by=.(Cancer_Code)
      ]))
  GT_probs_tmp<-suppressMessages(GT_probs_tmp         %>%
    dcast(
      . ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>% magrittr::set_rownames(paste(names(pathways[i]))) %>%
    .[, . := NULL] %>%
    data.matrix())
  return(GT_probs_tmp)
})

GT_probs_train<-do.call(rbind, GT_probs_train)

#############
#Test probs
#############

to_filt<-tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & Cancer_Code %in% c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC")]
to_filt$Cancer_Code<-factor(to_filt$Cancer_Code, levels=c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC"))

unique_train_vars<-unique(tcga_v_f_train$Variant)


tmp1<-to_filt[patient_id %in% test_ids,]
tmp1$Cancer_Code<-factor(tmp1$Cancer_Code, levels=c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC"))
denom<-tmp1[,.(denom=length(unique(patient_id))), by=.(Cancer_Code)][order(Cancer_Code),]

valid_probs<-lapply(1:length(pathways), FUN=function(i){
  if(i%%50==0){print(i)}
  genes_of_interest<-pathways[[i]]
  tmp<-tmp1[Hugo_Symbol %in% genes_of_interest,]
  tmp<-tmp[Variant %!in% unique_train_vars,]
  tmp<-suppressMessages(tmp %>% group_by(Cancer_Code, .drop=FALSE) %>% summarize(num=length(unique(patient_id))))
  return(tmp$num/denom$denom)
})


valid_probs<-do.call(rbind, valid_probs)
rownames(valid_probs)<-names(pathways)
colnames(valid_probs)<-c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC")

############
#bring em together
############

trainprobs<-GT_probs_train %>% melt()
colnames(trainprobs)<-c("Path", "Cancer_Type", "x")

valid=valid_probs %>% melt()
colnames(valid)<-c("Path", "Cancer_Type", "y")


Lins<-epi.ccc(left_join(trainprobs, valid)$x, left_join(trainprobs, valid)$y)

png("valid_PMBG.png", units="in", width=8, height=8, res=350)
left_join(trainprobs, valid) %>% tibble() %>% ggplot(aes(x=x, y=y, color=Cancer_Type))+geom_point(alpha=0.2)+coord_fixed()+geom_abline(aes(intercept=0, slope=1))+annotate(geom="text", x=0.2, y=0.8, label=paste("Lin's CC: ", round(Lins$rho.c[1], 3)),
              color="red", cex=5)+theme_minimal()+xlab("Estimated from Train")+ylab("Observed in Test")
dev.off()

###########
#True test

to_filt<-tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & Cancer_Code %in% c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC")]
to_filt$Cancer_Code<-factor(to_filt$Cancer_Code, levels=c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC"))

denom<-suppressMessages(to_filt[patient_id %in% test_ids,] %>% group_by(Cancer_Code, .drop=FALSE) %>% summarize(denom=length(unique(patient_id))))

valid_probs<-mclapply(1:length(pathways), FUN=function(i){
  if(i%%10==0){print(i)}
  genes_of_interest<-pathways[[i]]
  tmp_vec<-c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC")
  tmp_list<-lapply(1:16, FUN=function(j){
    tmp<-to_filt[Cancer_Code==tmp_vec[j],]
    tmp<-tmp[patient_id %in% test_ids & Hugo_Symbol %in% genes_of_interest & Variant %!in% tcga_v_f_train[Cancer_Code==tmp_vec[j]]$Variant,]
    tmp<-length(unique(tmp$patient_id))
    tmp
  })
  return(unlist(tmp_list)/denom$denom)
}, mc.cores=8)

valid_probs<-do.call(rbind, valid_probs)
rownames(valid_probs)<-names(pathways)
colnames(valid_probs)<-c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC")


trainprobs<-GT_probs_train %>% melt()
colnames(trainprobs)<-c("Path", "Cancer_Type", "x")

valid=valid_probs %>% melt()
colnames(valid)<-c("Path", "Cancer_Type", "y")

Lins<-epi.ccc(left_join(trainprobs, valid)$x, left_join(trainprobs, valid)$y)

png("valid_PMBG.png", units="in", width=8, height=8, res=350)
left_join(trainprobs, valid) %>% tibble() %>% ggplot(aes(x=x, y=y, color=Cancer_Type))+geom_point(alpha=0.2)+coord_fixed()+geom_abline(aes(intercept=0, slope=1))+annotate(geom="text", x=0.2, y=0.8, label=paste("Lin's CC: ", round(Lins$rho.c[1], 3)),
              color="red", cex=5)+theme_minimal()+xlab("Estimated from Train")+ylab("Observed in Test")
dev.off()


######
#facet plot

Lins<-c()
for(cancer in c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC")){
  tmp<-left_join(trainprobs, valid) %>% dplyr::filter(.$Cancer_Type==cancer)
  Lins<-c(Lins, epi.ccc(tmp %>% dplyr::select(x) %>% .$x, tmp %>% dplyr::select(y) %>% .$y)$rho.c[1])
}
Lins<-unlist(Lins)

dat_text <- data.frame(
  Cancer_Type = c("BLCA", "BRCA", "COADREAD", "GBM", "HNSC", "KIRC", "KIRP", "LGG", "LIHC", "LUAD", "LUSC", "OV", "PRAD", "STAD", "THCA", "UCEC"),
  LCC   = Lins
)

png("PMBG_valid_facet.png", units="in", width=8, height=8, res=300)
left_join(trainprobs, valid) %>% tibble() %>% ggplot(aes(x=x, y=y, color=Cancer_Type))+geom_point()+coord_fixed()+geom_abline(aes(intercept=0, slope=1))+theme_minimal()+xlab("Estimated from Train")+ylab("Observed in Test")+facet_wrap(~Cancer_Type)+ geom_text(
  data    = dat_text,
  mapping = aes(x = 0.15, y = 0.75, label = paste("LCC:", round(LCC, 2))),
  cex=3
)
dev.off()

```

#Single mut

##probs heatmap cor to TMB
```{r}
GT_probs_single<-lapply(1:length(pathways), FUN=function(i){
  if(i%%100==0){print(i)}
  genes_of_interest<-pathways[[i]]
  tmp<-tcga_v_f[Hugo_Symbol %in% genes_of_interest,]
  tmp$Hugo_Symbol<-names(pathways[i])
  tmp$Cancer_Code<-factor(tmp$Cancer_Code, levels=sort(unique(tcga_v_f$Cancer_Code)))
  GT_probs_tmp=suppressMessages(suppressWarnings(tmp[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[2]),
      by=.(Cancer_Code)
      ]))
  
  GT_probs_tmp_1<-suppressMessages(GT_probs_tmp          %>%
    dcast(
      GT ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>%
    .[, GT := NULL] %>%
    data.matrix()) %>% colSums()
  
  GT_probs_tmp_1
})

GT_probs_single<-do.call("rbind", GT_probs_single)

rownames(GT_probs_single)<-names(pathways)
colnames(GT_probs_single)<-sort(unique(tcga_v_f$Cancer_Code))

library(RColorBrewer)
coul<- colorRampPalette(brewer.pal(20, "YlOrRd"))(25)
png("path_heatmap_single.png", units="in", width=8, height=8, res=300)
heatmap(GT_probs_single, Rowv=TRUE, Colv=NA, col=coul, scale="row", labRow=FALSE)
dev.off()

nmis<-calc_minfo(GT_probs_single, cancer_prob=cancer_probs, normalize=TRUE)

###find corr w/ TMB
scalar1<-function(x){x/sqrt(sum(x^2))}
TMB_vec<-tcga_v_f %>% dplyr::group_by(Cancer_Code) %>% dplyr::summarize(TMB=sum(v_f)/n_tumor[1]) %>% .$TMB %>% scalar1()

cors_single<-lapply(1:dim(GT_probs_single)[1], FUN=function(i) cor(TMB_vec, GT_probs_single[i,]))
png("cors_with_TMB_single.png", units="in", width=6, height=4, res=300)
ggplot()+geom_histogram(data=NULL, aes(x=unlist(cors_single), y=..count..), binwidth=0.01)+xlab("Correlations between Mut. Probs and TMB")+ylab("Frequency")+scale_fill_manual(values=c("red", "black"))+theme_minimal()+theme(legend.position='none')
dev.off()
```

##null nmis and nmi comparison
```{r}
set.seed(11)

setDTthreads(0)

tcga_samp<-tcga[
    # filter out all hypermutated tumors
    # & tumors with unknown cancer
    MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),
    ] %>% select(patient_id, Cancer_Code) %>% distinct()

tcga_null<-tcga

tcga_null<-lapply(1:length(pathways), FUN=function(i){
  tmp<-tcga_null[Hugo_Symbol %in% pathways[[i]],]
  tmp$Hugo_Symbol<-names(pathways[i])
  tmp})
tcga_null<-do.call("rbind", tcga_null)

############
#crank out null iterations

test<-function(i){
  #scramble tissue labels associated with each tumor

  tcga_samp$Cancer_Code<-sample(tcga_samp$Cancer_Code, replace=FALSE)

  tcga_p<-left_join(tcga_null[MS %in% c("Non-hypermutated", "APOBEC (2, 13)", "Smoking (4)", "MMR (6, 15, 20, 26)")  & !is.na(Cancer_Code),][,c(1,2,3)], tcga_samp, by='patient_id')

  
  tcga_v_f_p<-suppressWarnings(tcga_p[, # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      n_tumor := length(unique(patient_id)),
      by = .(Cancer_Code)][,
                          .(v_f = length(unique(patient_id)), Hugo_Symbol=Hugo_Symbol[1], n_tumor = n_tumor[1]),
                          by = .(Variant, Cancer_Code)
                          ])
  
#calc GT probs

GT_probs_perm=suppressMessages(suppressWarnings(tcga_v_f_p[,
      .(GT=goodturing_probs(v_f, m=n_tumor[1])[2]),
      by=.(Hugo_Symbol, Cancer_Code)
      ]))

GT_probs_1_perm<-suppressMessages(GT_probs_perm          %>%
    dcast(
      Hugo_Symbol ~ Cancer_Code,
      value.var = "GT",
      fill = 0,
      drop=FALSE
    ) %>%
    magrittr::set_rownames(.$Hugo_Symbol) %>%
    .[, Hugo_Symbol := NULL] %>%
    data.matrix())
  
  calc_minfo(GT_probs_1_perm, cancer_prob=cancer_probs, normalize=TRUE)}

null_nmis_sing<-mclapply(1:100, FUN=test, mc.cores = 8)

to_plot_nmi<-data.frame("val"=c(unlist(null_nmis_sing), nmis), "id"=c(rep("Null", length(unlist(null_nmis_sing))), rep("True", length(nmis))))

png("null_nmi_dist_single.png", units="in", width=7, height=5.5, res=300)
ggplot()+geom_histogram(data=to_plot_nmi[which(to_plot_nmi$id=="Null"),], aes(x=val, y=stat(count)/sum(count)), fill="blue", alpha=0.5)+geom_histogram(data=to_plot_nmi[which(to_plot_nmi$id=="True"),], aes(x=val, y=stat(count)/sum(count)), fill="red", alpha=0.5)+theme_classic()+geom_vline(aes(xintercept=quantile(unlist(null_nmis_sing), 0.99)), lty=2)+theme(legend.position="none")+xlab("NMI")+ylab("Relative Frequency")
dev.off()

###bubbleplot

GT_probs_single[which(nmis>quantile(unlist(null_nmis_sing), 0.99)),] %>% melt() %>% ggplot(aes(x=Var2, y=Var1, size=value, color=value))+geom_point()+scale_y_discrete(label=function(x) abbreviate(x, minlength = 16))+theme(legend.position="none", axis.text.x=element_text(angle=90))+scale_color_gradient2(low="gold", mid="orange", high="red")

png("top10nmi_bubble_sing.png", units="in", width=8, height=6, res=300)
GT_probs_single[which(rownames(GT_probs_single[which(nmis>quantile(unlist(null_nmis_sing), 0.99)),]) %in% names(sort(nmis, decreasing=TRUE))[1:10]),] %>% melt() %>% ggplot(aes(x=Var2, y=Var1, size=value, color=value))+geom_point()+scale_y_discrete(label=function(x) abbreviate(x, minlength = 16))+theme_minimal()+theme(legend.position="none", axis.text.x=element_text(angle=90), axis.title = element_blank())+scale_color_gradient2(low="gold", mid="orange", high="red")
dev.off()
```

