---
title: "Visualizing genes"
author: "Ethan Ashby"
date: "9/18/2020"
output: pdf_document
---

```{r setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(variantprobs)
library(data.table)
#the freaking best package for distances
library(philentropy)
library(heatmaply)

###initialize vector of similarities
similarities<-c("intersection", "czekanowski", "kulczynski", "ruzicka", "inner_product", "harmonic_mean", "cosine", "hassebrook", "fidelity")
```

```{r}
#dist.diversity gives a TON of different distances
dist.diversity(rbind(1:10/sum(1:10), 20:29/sum(20:29)), p = 2, unit = "log2")
```


```{r }
data(tcga)

tcga_nh <- data.table::setDT(tcga) %>% filter(MS=="Non-hypermutated")
num_samps<-length(unique(tcga_nh$patient_id))
tcga1<-tcga_nh %>% group_by(Hugo_Symbol) %>% dplyr::mutate("freq"=dplyr::n()/num_samps>0.03) %>% dplyr::filter(freq==TRUE)
tcga1<-as.data.table(tcga1)

tcga_v_f <- tcga1[
  # filter out all hypermutated tumors
  # & tumors with unknown cancer
  MS=="Non-hypermutated" & !is.na(Cancer_Code),
  ][
    ,
    # number of tumors per cancer type
    n_tumor := length(unique(patient_id)),
    by = Cancer_Code
    ][,
      # variant frequencies by gene, cancer type
      # also save n_tumor per cancer
      .(v_f = length(unique(patient_id)),
        n_tumor = n_tumor[1]),
      by = .(Variant, Hugo_Symbol, Cancer_Code)
      ]

probs<-suppressWarnings(tcga_v_f[,
        # Calculate Good Turing probabilities of
        # at least one new variants per CLUSTER & cancer type
        {
          GT_probs <- goodturing_probs(
          counts = v_f,
          m = n_tumor[1]
          )
          .(p_atleast_1new = GT_probs['atleast_1new'])
          },
          by = .(Hugo_Symbol, Cancer_Code)
          ] 
          %>%
          dcast(
                Hugo_Symbol ~ Cancer_Code,
                value.var = "p_atleast_1new",
                fill = 1 - exp(- 1/(length(unique(tcga$patient_id)) + 1))
                ) %>%
          magrittr::set_rownames(.$Hugo_Symbol) %>%
          .[, Hugo_Symbol := NULL] %>%
          data.matrix())


probs[c("OBSCN", "NEB"),] %>% melt() %>% ggplot(aes(x=Var2, y=Var1, size=value, color=Var1))+geom_point()
div<-dist.diversity(t(apply(probs, MARGIN=1, FUN=estimate.probability, method="empirical"))[c(1,2),], p = 2, unit = "log2")

norm_probs<-t(apply(probs, MARGIN=1, FUN=estimate.probability, method="empirical"))
cosine_dist_mat<-matrix(nrow=dim(norm_probs)[1], ncol=dim(norm_probs)[1])
for (i in 1:dim(norm_probs)[1]){
  for (j in 1:dim(norm_probs)[1]){
    cosine_dist_mat[i,j]<-cosine_dist(norm_probs[i,], norm_probs[j,], testNA=FALSE)
  }
}


heatmap(cosine_dist_mat, symm=TRUE, labRow=rownames(norm_probs), labCol=rownames(norm_probs))

rownames(cosine_dist_mat)<-rownames(norm_probs)
colnames(cosine_dist_mat)<-rownames(norm_probs)

p <- heatmaply(cosine_dist_mat, 
        dendrogram = "row",
        xlab = "", ylab = "", 
        main = "",
        margins = c(60,100,40,20),
        grid_color = "white",
        grid_width = 0.00001,
        titleX = FALSE,
        hide_colorbar = FALSE,
        symm=TRUE,
        revC=TRUE,
        branches_lwd = 0.1,
        label_names = c("Rowgene", "Colgene", "CosineSim"),
        scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
            low = "blue", 
            high = "red", 
            midpoint = 0.5, 
            limits = c(0, 1)
        ),
        fontsize_row = 5, fontsize_col = 5,
        labCol = colnames(cosine_dist_mat),
        labRow = rownames(cosine_dist_mat),
        heatmap_layers = theme(axis.line=element_blank())
        )
```

```{r fig.width=5, fig.height=5}
#######Function for visualizing distance between genes GT probs
`%!in%` = Negate(`%in%`)

vis_dist_GT_genes<-function(x=norm_probs, dist="cosine", which_plot="heatmaply"){
    if(dist %!in% getDistMethods()){stop("Error: please provide distance measure in getDistMethods()")}
    dist_mat<-distance(x, method=dist, test.na = FALSE)
    rownames(dist_mat)<-rownames(norm_probs)
    colnames(dist_mat)<-rownames(norm_probs)
    if(which_plot=="simple"){
      p<-heatmap(dist_mat, symm=TRUE)
      return(p)
    }
    
    row_dend  <- hclust(as.dist(dist_mat), method="average") %>% 
    as.dendrogram()
    
    if(which_plot=="heatmaply"){
      p <- heatmaply(dist_mat, 
        dendrogram = "both",
        xlab = "", ylab = "", 
        main = "",
        margins = c(60,100,40,20),
        grid_color = "white",
        grid_width = 0.00001,
        titleX = FALSE,
        hide_colorbar = FALSE,
        symm=TRUE,
        branches_lwd = 0.1,
        seriate="none",
        label_names = c("Rowgene", "Colgene", "CosineSim"),
        scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
            name=dist,
            low = "blue", 
            high = "red", 
            midpoint = mean(c(max(dist_mat), 0)), 
            limits = c(0, max(dist_mat))
        ),
        fontsize_row = 5, fontsize_col = 5,
        labCol = colnames(cosine_dist_mat),
        labRow = rownames(cosine_dist_mat),
        heatmap_layers = theme(axis.line=element_blank()),
        Rowv = row_dend
      )
      
      return(p)
    }
}

vis_dist_GT_genes(dist="cosine", which_plot = "simple")
vis_dist_GT_genes(dist="jensen-shannon", which_plot = "simple")
vis_dist_GT_genes(dist="kullback-leibler", which_plot = "simple")
vis_dist_GT_genes(dist="bhattacharyya", which_plot = "simple")
vis_dist_GT_genes(dist="hellinger", which_plot = "simple")
vis_dist_GT_genes(dist="k_divergence", which_plot = "simple")
vis_dist_GT_genes(dist="squared_chi", which_plot = "simple")

vis_dist_GT_genes(dist="cosine")



#####Generates hierarchies based on two distance metrics and compares them by cut length

compare_hclust_results<-function(x=norm_probs, method1, method2, cut_depth=dim(norm_probs)[1]-1, plot=FALSE){
  #return some errors if unsupported metrics provided
  if(method1 %!in% getDistMethods()){stop("Error: please provide distance measure in getDistMethods()")}
  if(method2 %!in% getDistMethods()){stop("Error: please provide distance measure in getDistMethods()")}
  
  #initialize local function that calculates FM_index to compare k-cuts of two hierarchies
  fo <- function(k) dendextend::FM_index_R(cutree(HC1, k), cutree(HC2, k))
  
  #############
  ###First hierarchy built on distance/similarity
  #############
  d1<-distance(x, method=method1, test.na=FALSE, p=2, unit="log2")
  rownames(d1)<-rownames(x)
  colnames(d1)<-rownames(x)
  d1<-as.matrix(d1)
  
  #if kulczynski similarity do 1/sim matrix to get dist
  if(method1 =="kulczynski"){
  HC1<-hclust(as.dist(1/d1), method="average")
  }
  #if in this group, use 1-sim to get dist
  if(method1 %in% c("motyka", "intersection", "czekanowski", "cosine")){
  HC1<-hclust(as.dist(1-d1), method="average")
  }
  #if in this group, use max-sim to get dist
  if (method1 %in% c("ruzicka", "inner_product", "harmonic_mean", "hassebrook", "fidelity"))
  {
  HC1<-hclust(as.dist(max(d1)-d1), method="average")
  }
  #if a true distance metric, just leave it be
  if (method1 %!in% similarities){
  HC1<-hclust(as.dist(d1), method="average")
  }

  #plot(HC, labels = rownames(d1), hang = 0.1, check = TRUE,
     #axes = TRUE, frame.plot = FALSE, ann = TRUE,
     #main = "Cluster Dendrogram",
     #sub = NULL, xlab = NULL, ylab = "Height")
  
  ###############
  ###Second hierarchy built on distance/similarity
  ###############
  
  d2<-distance(x, method=method2, test.na=FALSE, p=2, unit="log2")
  rownames(d2)<-rownames(x)
  colnames(d2)<-rownames(x)
  d2<-as.matrix(d2)
  
  #if kulczynski similarity do 1/sim matrix to get dist
  if(method2 =="kulczynski"){
  HC2<-hclust(as.dist(1/d2), method="average")
  }
  #if in this group, use 2-sim to get dist
  if (method2 %in% c("motyka", "intersection", "czekanowski", "cosine")){
  HC2<-hclust(as.dist(1-d2), method="average")
  }
  #if in this group, use max-sim to get dist
  if (method2 %in% c("ruzicka", "inner_product", "harmonic_mean", "hassebrook", "fidelity"))
  {
  HC2<-hclust(as.dist(max(d2)-d2), method="average")
  }
  #if a true distance metric, just leave it be
  if (method2 %!in% similarities){
  HC2<-hclust(as.dist(d2), method="average")
  }

  ks=1:cut_depth
  if(plot==TRUE) {plot(sapply(ks, fo)~ ks, type="b", main="BK plot comparing")}
  if(plot==FALSE){
    fm_indices<-sapply(ks, fo)
    fm_indices
  }
}

#compare_hclust_results(method1="cosine", method2="euclidean", plot=TRUE)

#creates r plot faceted by comparison metric; FM metric vs cut
#generates interactive plotly plot at bottom
faceted_FM_plot<-function(dist_to_compare=NULL, cut_depth=10){
if(is.null(dist_to_compare)){dist_to_compare<-getDistMethods()}
df<-data.frame()

suppressWarnings(suppressMessages(
for (i in 1:length(dist_to_compare)){
  mat<-matrix(nrow=length(dist_to_compare), ncol=cut_depth)
  rownames(mat)<-dist_to_compare
  colnames(mat)<-1:cut_depth
  for (j in 1:length(dist_to_compare)){
    mat[j,]<-compare_hclust_results(method1=dist_to_compare[i], method2=dist_to_compare[j], cut_depth=cut_depth)
  }
  tmp<-mat %>% melt()
  colnames(tmp)<-c("metric", "dendrocut_k", "FM_index")
  tmp$ref<-dist_to_compare[i]
  df<-rbind(df, tmp) 
}
))

df %>% ggplot()+geom_line(aes(x=dendrocut_k, y=FM_index, color=metric))+theme_bw()+theme(panel.grid = element_blank(), panel.background = element_rect(fill="black"))+facet_wrap(~ref)+guides(col=guide_legend(reverse=TRUE))
}

g<-faceted_FM_plot(cut_depth=20)
fig<-ggplotly(g)
fig


#creates dendrogram comparing distance metrics
faceted_FM_dendrograpm<-function(dist_to_compare=NULL, cut_depth=10){
  if(is.null(dist_to_compare)){dist_to_compare<-getDistMethods()}
  
  mat<-matrix(nrow=length(dist_to_compare), ncol=length(dist_to_compare))
  rownames(mat)<-dist_to_compare
  colnames(mat)<-dist_to_compare
  suppressMessages(
  for (i in 1:length(dist_to_compare)){
    mat[i,]<-lapply(X=dist_to_compare, FUN=function(X){tail(compare_hclust_results(method1=dist_to_compare[i], method2=X, cut_depth = cut_depth), 1)}) %>% unlist()
  }
)

  #hclust operates on dissimilarity
  dend_dmetrics<-hclust(as.dist(mat), method="average")
  plot(dend_dmetrics, main="Cluster dendrogram of distance metrics")
}

faceted_FM_dendrograpm(cut_depth=40)


```

